/**
 * Copyright (c) 2014 Comity Designs
 * All rights reserved.
 *
 * This class is Invalid operation exception class for the Renewal Manager.
 *
 * History:
 * =========================================
 * Developer         Date        description
 * --------------------------------------------------------------------------------------------------
 * Ivan Melnikov     07/30/2014  Code refactoring 
 *
 * 
 **/
public class InvalidOperationException extends Exception {

}